config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :address, presence: true, uniqueness: true
  validates :name, presence: true
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  validates :category, presence: true, inclusion: { in: CATEGORIES, message: "That is not a valid category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    # @review = @restaurant.review
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private
  def restaurant_params
    params[:restaurant].permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private
  def review_params
    params[:review].permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :category, collection: Restaurant::CATEGORIES.map { |category| category.capitalize }, prompt: "Select a category" %>
  <%= f.submit "Submit", class:"btn btn-success" %>
<% end %>

app/views/restaurants/destroy.html.erb
<h1>Restaurants#destroy</h1>
<p>Find me in app/views/restaurants/destroy.html.erb</p>

app/views/restaurants/edit.html.erb
<h1>Restaurants#edit</h1>
<p>Find me in app/views/restaurants/edit.html.erb</p>

app/views/restaurants/index.html.erb
<div class="container mt-3">
  <h1>All restaurants</h1>

  <% @restaurants.each do |r| %>
    <ul>
      <li>
        <p><strong><%= r.name %></strong></p>
        <p><%= r.address %></p>
        <p><%= r.category.capitalize %></p>
      </li>
    </ul>
  <% end %>
</div>

app/views/restaurants/new.html.erb
<div class="container mt-5">
  <h1>Add New Restaurant</h1>
  <p>Please fill the form below</p>
  <%= render "form" %>
</div>

app/views/restaurants/show.html.erb
<div class="container my-5">
  <h1><%= @restaurant.name %></h1>
    <p><%= @restaurant.address %></p>
    <p><%= @restaurant.category.capitalize %></p>
</div>

<div class="container">
  <h1>All Reviews</h1>
  <ul>
      <% if @restaurant.reviews.any? %>
        <% @restaurant.reviews.each do |review| %>
          <li>
            <%= review.content %>
            <%= link_to 'x', review_path(review), data: { turbo_method: :delete, turbo_confirm: 'Delete Review?' } %>
          </li>
        <% end %>
      <% else %>
        <li>No reviews yet.</li>
      <% end %>
      <p><%= link_to 'Add Review', new_restaurant_review_path(@restaurant) %></p>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating, collection: (1..5).to_a %>
  <%= f.submit 'Submit', class:'btn btn-info mt-2' %>
<% end %>

app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

app/views/reviews/new.html.erb
<div class="container mt-5">
  <h1>Add Review To Restaurant</h1>
  <p>Please fill the form below</p>
  <%= render 'form' %>
</div>